name: Rector

on:
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: write

jobs:
  rector:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
 
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
 
      - run: vendor/bin/rector --ansi
 
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: always()